############################
# Input files
input:
    amplicons: "~/Documents/Single_Cell_Project/mdasim2.0/outAmplicons.fasta"
    reference: "~/Documents/Single_Cell_Project/mdasim2.0/examples/test.fa"
